name: build

on: push

jobs:

  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

      - name: run
        run: |
          make

  quickrelease:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

      - name: run
        run: |
          make quick-release

  e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

      - name: run
        run: |
          make all WHAT="cmd/kubectl test/e2e/e2e.test