name: build

on: 
  push:
    branches: [ build_k8s ]

jobs:

  kind:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

      - name: run
        run: |
          wget -q https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-linux-amd64
          chmod +x kind-linux-amd64
          mv kind-linux-amd64 /usr/local/bin/kind
          mkdir tmp
          cd tmp
          kind build node-image --image ghcr.io/liangyuanpeng/kindest/node:latest --kube-root $PWD/../
          tree . 
          docker images


  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

      - name: run
        run: |
          make

  # quickrelease:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Git checkout
  #       uses: actions/checkout@v3

  #     - name: install Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.20.6

  #     - name: run
  #       run: |
  #         make quick-release

  e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

#https://github.com/kubernetes-sigs/kind/blob/main/hack/ci/e2e-k8s.sh
      - name: run
        run: |
          make all WHAT="cmd/kubectl test/e2e/e2e.test"