name: build

on: 
  push:
    branches: [ build_k8s ]

jobs:

  # ci:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Git checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 1

  #     - name: install Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.20.6

  #     - name: run
  #       run: |
  #         make

  quickrelease:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

      - name: run
        run: |
            export KUBE_DOCKER_REGISTRY=ghcr.io
            export VERSION=`git describe`
            echo "begin make"
            docker rmi `docker images -aq`
            make quick-release-images
            docker images
            ls _output
            echo "======================="
            ls _output/release-images
            echo "======================="
            ls _output/images
            echo "======================="
            tree _output
            echo "======================="
            rm -rf _output/dockerized
            rm -rf _output/release-stage
            docker load -i _output/release-images/amd64/kube-apiserver.tar
            docker load -i _output/release-images/amd64/kube-controller-manager.tar
            docker load -i _output/release-images/amd64/kube-proxy.tar
            docker load -i _output/release-images/amd64/kube-scheduler.tar
            docker images
            docker tag registry.k8s.io/kube-apiserver-amd64:$VERSION ghcr.io/liangyuanpeng/kube-apiserver-amd64:$VERSION
            docker tag registry.k8s.io/kube-controller-manager-amd64:$VERSION ghcr.io/liangyuanpeng/kube-controller-manager-amd64:$VERSION
            docker tag registry.k8s.io/kube-proxy-amd64:$VERSION ghcr.io/liangyuanpeng/kube-proxy-amd64:$VERSION
            docker tag registry.k8s.io/kube-scheduler-amd64:$VERSION ghcr.io/liangyuanpeng/kube-scheduler-amd64:$VERSION
            docker login ghcr.io -uliangyuanpeng -p${{ secrets.GH_PACKAGE_TOKEN }}
            docker push ghcr.io/liangyuanpeng/kube-apiserver-amd64:$VERSION
            docker push ghcr.io/liangyuanpeng/kube-controller-manager-amd64:$VERSION
            docker push ghcr.io/liangyuanpeng/kube-proxy-amd64:$VERSION
            docker push ghcr.io/liangyuanpeng/kube-scheduler-amd64:$VERSION
            docker logout

  e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

#https://github.com/kubernetes-sigs/kind/blob/main/hack/ci/e2e-k8s.sh
      - name: run
        run: |
          make all WHAT="cmd/kubectl test/e2e/e2e.test"