#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: k8s_ci
on:
  push:
  workflow_call:
  workflow_dispatch:
    inputs:
      ref:
        description: 'source ref of kubernetes '
        required: true
        default: "master"
      repo:
        description: 'repo of kubernetes'
        required: false
        default: "kubernetes/kubernetes"

jobs:

  ci:
    name: ci
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        kindnode: 
        - ghcr.io/liangyuanpeng/kindest/node:v0.20.0-v1.29.0-alpha.0-745-ga657643dd0c
        - kindest/node:v1.28.0
    steps:
      - name: pull
        run: |
          ls -allh
          pwd
          nohup ${{ matrix.kindnode }} &
          nohup docker pull ghcr.io/liangyuanpeng/ubuntu:tools-v1.1 &
      - name: checkoutactions
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # - uses: actions/setup-go@v3
      #   with:
      #     go-version: '1.20'

      - uses: oras-project/setup-oras@v1
        with:
          version: 1.0.0

      - name: clean
        run: |
          nohup docker rmi `docker images -aq` &
          rm -rf /opt/hostedtoolcache/CodeQL
          rm -rf /opt/hostedtoolcache/node
          rm -rf /opt/hostedtoolcache/Python

      - name: download kind
        run: |
          wget -q https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-linux-amd64
          chmod +x kind-linux-amd64 &&  mv kind-linux-amd64 /usr/local/bin/kind

      - name: create cluster with kind
        run: |
          sed -i 's#NODEIMG#'${{ matrix.kindnode }}'#g'  hack/kind-config.yaml
          kind create cluster --config hack/kind-config.yaml
          docker pull ghcr.io/liangyuanpeng/ubuntu:tools-v1.1
          kind load docker-image ghcr.io/liangyuanpeng/ubuntu:tools-v1.1
          kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --group=system:serviceaccounts
          kubectl apply -f hack/job.yaml
          kubectl wait node --all --for condition=ready

      - name: run ci
        run: |
          kubectl get po -A 
          jobpod=$(kubectl get pods --selector=app=kubernetes --output=jsonpath='{.items[*].metadata.name}')
          kubectl wait pod --for=condition=Ready=true $jobpod
          kubectl get po 

      - name: check logs
        run: |
          jobpod=$(kubectl get pods --selector=app=kubernetes --output=jsonpath='{.items[*].metadata.name}')
          kubectl logs $jobpod -f 
          kubectl get po 
          kubectl get job
          job_status=$(kubectl get job k8s -o jsonpath='{.status.conditions[0].type}')
          echo "job status is :"$job_status
          
      - name: check status
        run: |
          sleep 2
          kubectl get job
          kubectl get po 
          job_status=$(kubectl get job k8s -o jsonpath='{.status.conditions[0].type}')
          echo "job status is :"$job_status
          if [ "$job_status" = "Complete" ]; then
            exit 0
          else
            exit 1
          fi

      - uses: chainguard-dev/actions/kind-diag@main
        if: always()
        with:
          cluster-resources: nodes,namespaces,
          namespace-resources: configmaps,pods,svc
          artifact-name: kindlogs