name: kubetest
#https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md

on:
  push:
    # branches: [ build_k8s ]

jobs:

  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

      - uses: oras-project/setup-oras@v1
        with:
          version: 1.0.0

      - name: install kubetest
        run: |
          #git clone https://github.com/kubernetes/test-infra.git
          #cd test-infra
          #go install k8s.io/test-infra/kubetest
          #cd .. 
          #rm -rf test-infra
          oras pull ghcr.io/liangyuanpeng/files:kubetest
          mv kubetest /usr/local/bin/

      - name: run
        run: |
          cd .. 
          docker rmi `docker images -aq`
          df -h
          mkdir -p /home/runner/go/src/k8s.io
          mv kubernetes /home/runner/go/src/k8s.io/
          chmod -R 777 /home/runner/go/src/k8s.io/kubernetes
          cd /home/runner/go/src/k8s.io/kubernetes
          #kubetest --build --up --test --test_args="--ginkgo.focus=\[StatefulSet\]" --provider=local
          kubetest --build --up --test --test_args="--ginkgo.focus=\[StatefulSet\]" --down
          #cd test/e2e 
          #go get github.com/onsi/ginkgo/v2
          #ginkgo --focus="\[StatefulSet\]"